#ifndef __GENERATED_alremoteproxies__
#define __GENERATED_alremoteproxies__
#include <alremoteproxies/alpythonbridgeproxyremote.h>
#include <alremoteproxies/almemoryproxyremote.h>
#include <alremoteproxies/alredballtrackerproxyposthandlerremote.h>
#include <alremoteproxies/alsounddetectionproxyposthandlerremote.h>
#include <alremoteproxies/alsounddetectionproxyremote.h>
#include <alremoteproxies/alsentinelproxyremote.h>
#include <alremoteproxies/alfsrproxyremote.h>
#include <alremoteproxies/alsonarproxyposthandlerremote.h>
#include <alremoteproxies/alaudioplayerproxyposthandlerremote.h>
#include <alremoteproxies/alredballdetectionproxyposthandlerremote.h>
#include <alremoteproxies/allauncherproxyposthandlerremote.h>
#include <alremoteproxies/alframemanagerproxyremote.h>
#include <alremoteproxies/alfacedetectionproxyremote.h>
#include <alremoteproxies/alvisiontoolboxproxyremote.h>
#include <alremoteproxies/alaudiosourcelocalizationproxyremote.h>
#include <alremoteproxies/albatteryproxyremote.h>
#include <alremoteproxies/alinfraredproxyposthandlerremote.h>
#include <alremoteproxies/alsensorsproxyremote.h>
#include <alremoteproxies/alrobotposeproxyremote.h>
#include <alremoteproxies/allaserproxyposthandlerremote.h>
#include <alremoteproxies/allauncherproxyremote.h>
#include <alremoteproxies/alfacetrackerproxyposthandlerremote.h>
#include <alremoteproxies/alvideodeviceproxyposthandlerremote.h>
#include <alremoteproxies/alfsrproxyposthandlerremote.h>
#include <alremoteproxies/alfilemanagerproxyposthandlerremote.h>
#include <alremoteproxies/alpreferencesproxyremote.h>
#include <alremoteproxies/alloggerproxyposthandlerremote.h>
#include <alremoteproxies/almotionproxyposthandlerremote.h>
#include <alremoteproxies/almotionproxyremote.h>
#include <alremoteproxies/alsentinelproxyposthandlerremote.h>
#include <alremoteproxies/alfacetrackerproxyremote.h>
#include <alremoteproxies/alaudiodeviceproxyremote.h>
#include <alremoteproxies/albonjourproxyremote.h>
#include <alremoteproxies/alledsproxyremote.h>
#include <alremoteproxies/alspeechrecognitionproxyposthandlerremote.h>
#include <alremoteproxies/alrobotposeproxyposthandlerremote.h>
#include <alremoteproxies/dcmproxyremote.h>
#include <alremoteproxies/albatteryproxyposthandlerremote.h>
#include <alremoteproxies/alpreferencesproxyposthandlerremote.h>
#include <alremoteproxies/almotionrecorderproxyremote.h>
#include <alremoteproxies/alfilemanagerproxyremote.h>
#include <alremoteproxies/alsensorsproxyposthandlerremote.h>
#include <alremoteproxies/alloggerproxyremote.h>
#include <alremoteproxies/alledsproxyposthandlerremote.h>
#include <alremoteproxies/altexttospeechproxyposthandlerremote.h>
#include <alremoteproxies/alaudiorecorderproxyposthandlerremote.h>
#include <alremoteproxies/almotionrecorderproxyposthandlerremote.h>
#include <alremoteproxies/alresourcemanagerproxyposthandlerremote.h>
#include <alremoteproxies/allaserproxyremote.h>
#include <alremoteproxies/allandmarkdetectionproxyposthandlerremote.h>
#include <alremoteproxies/alspeechrecognitionproxyremote.h>
#include <alremoteproxies/albehaviormanagerproxyremote.h>
#include <alremoteproxies/alvisionrecognitionproxyposthandlerremote.h>
#include <alremoteproxies/altexttospeechproxyremote.h>
#include <alremoteproxies/alvisiontoolboxproxyposthandlerremote.h>
#include <alremoteproxies/alsonarproxyremote.h>
#include <alremoteproxies/dcmproxyposthandlerremote.h>
#include <alremoteproxies/albehaviormanagerproxyposthandlerremote.h>
#include <alremoteproxies/alredballtrackerproxyremote.h>
#include <alremoteproxies/albonjourproxyposthandlerremote.h>
#include <alremoteproxies/alaudiosourcelocalizationproxyposthandlerremote.h>
#include <alremoteproxies/alaudiorecorderproxyremote.h>
#include <alremoteproxies/alvisionrecognitionproxyremote.h>
#include <alremoteproxies/alfacedetectionproxyposthandlerremote.h>
#include <alremoteproxies/alresourcemanagerproxyremote.h>
#include <alremoteproxies/alinfraredproxyremote.h>
#include <alremoteproxies/alaudioplayerproxyremote.h>
#include <alremoteproxies/alvideodeviceproxyremote.h>
#include <alremoteproxies/alaudiodeviceproxyposthandlerremote.h>
#include <alremoteproxies/alpythonbridgeproxyposthandlerremote.h>
#include <alremoteproxies/almemoryproxyposthandlerremote.h>
#include <alremoteproxies/alframemanagerproxyposthandlerremote.h>
#include <alremoteproxies/alredballdetectionproxyremote.h>
#include <alremoteproxies/allandmarkdetectionproxyremote.h>
#endif
