# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(LIBTHREAD_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(LIBTHREAD_INCLUDE_DIRS)
   
set(LIBTHREAD_DEPENDS "QI;ALERROR;BOOST;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;QI;ALERROR;BOOST;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL" CACHE STRING "" FORCE)
mark_as_advanced(LIBTHREAD_DEPENDS)

set(LIBTHREAD_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(LIBTHREAD_DEFINITIONS)
 

find_library(LIBTHREAD_DEBUG_LIBRARY althread_d)
find_library(LIBTHREAD_LIBRARY       althread)


if (LIBTHREAD_DEBUG_LIBRARY)
  set(LIBTHREAD_LIBRARIES optimized;${LIBTHREAD_LIBRARY};debug;${LIBTHREAD_DEBUG_LIBRARY})
else()
  set(LIBTHREAD_LIBRARIES ${LIBTHREAD_LIBRARY})
endif()
set(LIBTHREAD_LIBRARIES "${LIBTHREAD_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(LIBTHREAD_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBTHREAD DEFAULT_MSG
  LIBTHREAD_LIBRARIES
  LIBTHREAD_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(LIBTHREAD_PACKAGE_FOUND ${LIBTHREAD_FOUND} CACHE INTERNAL "" FORCE)
 
message(WARNING ${CMAKE_CURRENT_LIST_FILE}"
  Usage of :
    use_lib(... LIBTHREAD)
  is deprecated
  Use:
    qi_use_lib(... althread)
    or
    use_lib(... ALTHREAD)
   instead
")
