# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(LIBCORE_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(LIBCORE_INCLUDE_DIRS)
   
set(LIBCORE_DEPENDS "QI;ALERROR" CACHE STRING "" FORCE)
mark_as_advanced(LIBCORE_DEPENDS)

set(LIBCORE_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(LIBCORE_DEFINITIONS)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBCORE DEFAULT_MSG
  LIBCORE_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(LIBCORE_PACKAGE_FOUND ${LIBCORE_FOUND} CACHE INTERNAL "" FORCE)
 
if(NOT LIBCORE_I_KNOW_IT_IS_DEPRECATED AND QI_WARN_DEPRECATED)
  message(STATUS "
    ${CMAKE_CURRENT_SOURCE_DIR}: LIBCORE is deprecated
    please use libqi.
  "
  )
  set(LIBCORE_I_KNOW_IT_IS_DEPRECATED ON)
endif()
