# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALERROR_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALERROR_INCLUDE_DIRS)
   
set(ALERROR_DEPENDS "" CACHE STRING "" FORCE)
mark_as_advanced(ALERROR_DEPENDS)

set(ALERROR_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALERROR_DEFINITIONS)
 

find_library(ALERROR_DEBUG_LIBRARY alerror_d)
find_library(ALERROR_LIBRARY       alerror)


if (ALERROR_DEBUG_LIBRARY)
  set(ALERROR_LIBRARIES optimized;${ALERROR_LIBRARY};debug;${ALERROR_DEBUG_LIBRARY})
else()
  set(ALERROR_LIBRARIES ${ALERROR_LIBRARY})
endif()
set(ALERROR_LIBRARIES "${ALERROR_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALERROR_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALERROR DEFAULT_MSG
  ALERROR_LIBRARIES
  ALERROR_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALERROR_PACKAGE_FOUND ${ALERROR_FOUND} CACHE INTERNAL "" FORCE)
 