# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALBEHAVIORINFO_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALBEHAVIORINFO_INCLUDE_DIRS)
   
set(ALBEHAVIORINFO_DEPENDS "" CACHE STRING "" FORCE)
mark_as_advanced(ALBEHAVIORINFO_DEPENDS)

set(ALBEHAVIORINFO_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALBEHAVIORINFO_DEFINITIONS)
 

find_library(ALBEHAVIORINFO_DEBUG_LIBRARY albehaviorinfo_d)
find_library(ALBEHAVIORINFO_LIBRARY       albehaviorinfo)


if (ALBEHAVIORINFO_DEBUG_LIBRARY)
  set(ALBEHAVIORINFO_LIBRARIES optimized;${ALBEHAVIORINFO_LIBRARY};debug;${ALBEHAVIORINFO_DEBUG_LIBRARY})
else()
  set(ALBEHAVIORINFO_LIBRARIES ${ALBEHAVIORINFO_LIBRARY})
endif()
set(ALBEHAVIORINFO_LIBRARIES "${ALBEHAVIORINFO_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALBEHAVIORINFO_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALBEHAVIORINFO DEFAULT_MSG
  ALBEHAVIORINFO_LIBRARIES
  ALBEHAVIORINFO_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALBEHAVIORINFO_PACKAGE_FOUND ${ALBEHAVIORINFO_FOUND} CACHE INTERNAL "" FORCE)
 