# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALTHREAD_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALTHREAD_INCLUDE_DIRS)
   
set(ALTHREAD_DEPENDS "QI;ALERROR;BOOST;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;QI;ALERROR;BOOST;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL" CACHE STRING "" FORCE)
mark_as_advanced(ALTHREAD_DEPENDS)

set(ALTHREAD_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALTHREAD_DEFINITIONS)
 

find_library(ALTHREAD_DEBUG_LIBRARY althread_d)
find_library(ALTHREAD_LIBRARY       althread)


if (ALTHREAD_DEBUG_LIBRARY)
  set(ALTHREAD_LIBRARIES optimized;${ALTHREAD_LIBRARY};debug;${ALTHREAD_DEBUG_LIBRARY})
else()
  set(ALTHREAD_LIBRARIES ${ALTHREAD_LIBRARY})
endif()
set(ALTHREAD_LIBRARIES "${ALTHREAD_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALTHREAD_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALTHREAD DEFAULT_MSG
  ALTHREAD_LIBRARIES
  ALTHREAD_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALTHREAD_PACKAGE_FOUND ${ALTHREAD_FOUND} CACHE INTERNAL "" FORCE)
 