# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(QPOASES_INCLUDE_DIRS "${ROOT_DIR}/include;${ROOT_DIR}/include/qpoases;${ROOT_DIR}/include/qpoases3" CACHE STRING "" FORCE)
mark_as_advanced(QPOASES_INCLUDE_DIRS)
   
set(QPOASES_DEPENDS "" CACHE STRING "" FORCE)
mark_as_advanced(QPOASES_DEPENDS)

set(QPOASES_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(QPOASES_DEFINITIONS)
 

find_library(QPOASES_DEBUG_LIBRARY qpoases_d)
find_library(QPOASES_LIBRARY       qpoases)


if (QPOASES_DEBUG_LIBRARY)
  set(QPOASES_LIBRARIES optimized;${QPOASES_LIBRARY};debug;${QPOASES_DEBUG_LIBRARY})
else()
  set(QPOASES_LIBRARIES ${QPOASES_LIBRARY})
endif()
set(QPOASES_LIBRARIES "${QPOASES_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(QPOASES_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QPOASES DEFAULT_MSG
  QPOASES_LIBRARIES
  QPOASES_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(QPOASES_PACKAGE_FOUND ${QPOASES_FOUND} CACHE INTERNAL "" FORCE)
 