# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALTTS_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALTTS_INCLUDE_DIRS)
   
set(ALTTS_DEPENDS "ALTHREAD;ALLOG;BOOST;ALTOOLS;ALCORE;QI;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;ALERROR;BOOST_SIGNALS;ALTHREAD;ALLOG;BOOST;ALTOOLS;ALCORE;QI;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;ALERROR;BOOST_SIGNALS" CACHE STRING "" FORCE)
mark_as_advanced(ALTTS_DEPENDS)

set(ALTTS_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALTTS_DEFINITIONS)
 

find_library(ALTTS_DEBUG_LIBRARY altts_d)
find_library(ALTTS_LIBRARY       altts)


if (ALTTS_DEBUG_LIBRARY)
  set(ALTTS_LIBRARIES optimized;${ALTTS_LIBRARY};debug;${ALTTS_DEBUG_LIBRARY})
else()
  set(ALTTS_LIBRARIES ${ALTTS_LIBRARY})
endif()
set(ALTTS_LIBRARIES "${ALTTS_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALTTS_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALTTS DEFAULT_MSG
  ALTTS_LIBRARIES
  ALTTS_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALTTS_PACKAGE_FOUND ${ALTTS_FOUND} CACHE INTERNAL "" FORCE)
 