# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALPARAMMANAGER_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALPARAMMANAGER_INCLUDE_DIRS)
   
set(ALPARAMMANAGER_DEPENDS "" CACHE STRING "" FORCE)
mark_as_advanced(ALPARAMMANAGER_DEPENDS)

set(ALPARAMMANAGER_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALPARAMMANAGER_DEFINITIONS)
 

find_library(ALPARAMMANAGER_DEBUG_LIBRARY alparammanager_d)
find_library(ALPARAMMANAGER_LIBRARY       alparammanager)


if (ALPARAMMANAGER_DEBUG_LIBRARY)
  set(ALPARAMMANAGER_LIBRARIES optimized;${ALPARAMMANAGER_LIBRARY};debug;${ALPARAMMANAGER_DEBUG_LIBRARY})
else()
  set(ALPARAMMANAGER_LIBRARIES ${ALPARAMMANAGER_LIBRARY})
endif()
set(ALPARAMMANAGER_LIBRARIES "${ALPARAMMANAGER_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALPARAMMANAGER_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALPARAMMANAGER DEFAULT_MSG
  ALPARAMMANAGER_LIBRARIES
  ALPARAMMANAGER_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALPARAMMANAGER_PACKAGE_FOUND ${ALPARAMMANAGER_FOUND} CACHE INTERNAL "" FORCE)
 