# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(LIBBEHAVIORINFO_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(LIBBEHAVIORINFO_INCLUDE_DIRS)
   
set(LIBBEHAVIORINFO_DEPENDS "" CACHE STRING "" FORCE)
mark_as_advanced(LIBBEHAVIORINFO_DEPENDS)

set(LIBBEHAVIORINFO_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(LIBBEHAVIORINFO_DEFINITIONS)
 

find_library(LIBBEHAVIORINFO_DEBUG_LIBRARY albehaviorinfo_d)
find_library(LIBBEHAVIORINFO_LIBRARY       albehaviorinfo)


if (LIBBEHAVIORINFO_DEBUG_LIBRARY)
  set(LIBBEHAVIORINFO_LIBRARIES optimized;${LIBBEHAVIORINFO_LIBRARY};debug;${LIBBEHAVIORINFO_DEBUG_LIBRARY})
else()
  set(LIBBEHAVIORINFO_LIBRARIES ${LIBBEHAVIORINFO_LIBRARY})
endif()
set(LIBBEHAVIORINFO_LIBRARIES "${LIBBEHAVIORINFO_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(LIBBEHAVIORINFO_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBBEHAVIORINFO DEFAULT_MSG
  LIBBEHAVIORINFO_LIBRARIES
  LIBBEHAVIORINFO_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(LIBBEHAVIORINFO_PACKAGE_FOUND ${LIBBEHAVIORINFO_FOUND} CACHE INTERNAL "" FORCE)
 
message(WARNING ${CMAKE_CURRENT_LIST_FILE}"
  Usage of :
    use_lib(... LIBBEHAVIORINFO)
  is deprecated
  Use:
    qi_use_lib(... albehaviorinfo)
    or
    use_lib(... ALBEHAVIORINFO)
   instead
")
