# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALMATHINTERNAL_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALMATHINTERNAL_INCLUDE_DIRS)
   
set(ALMATHINTERNAL_DEPENDS "ALMATH;ALMATH" CACHE STRING "" FORCE)
mark_as_advanced(ALMATHINTERNAL_DEPENDS)

set(ALMATHINTERNAL_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALMATHINTERNAL_DEFINITIONS)
 

find_library(ALMATHINTERNAL_DEBUG_LIBRARY almathinternal_d)
find_library(ALMATHINTERNAL_LIBRARY       almathinternal)


if (ALMATHINTERNAL_DEBUG_LIBRARY)
  set(ALMATHINTERNAL_LIBRARIES optimized;${ALMATHINTERNAL_LIBRARY};debug;${ALMATHINTERNAL_DEBUG_LIBRARY})
else()
  set(ALMATHINTERNAL_LIBRARIES ${ALMATHINTERNAL_LIBRARY})
endif()
set(ALMATHINTERNAL_LIBRARIES "${ALMATHINTERNAL_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALMATHINTERNAL_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALMATHINTERNAL DEFAULT_MSG
  ALMATHINTERNAL_LIBRARIES
  ALMATHINTERNAL_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALMATHINTERNAL_PACKAGE_FOUND ${ALMATHINTERNAL_FOUND} CACHE INTERNAL "" FORCE)
 