# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALSOAP_INCLUDE_DIRS "${ROOT_DIR}/include;${ROOT_DIR}/include/soap;${ROOT_DIR}/include/alsoap" CACHE STRING "" FORCE)
mark_as_advanced(ALSOAP_INCLUDE_DIRS)
   
set(ALSOAP_DEPENDS "ALVALUE;TINYXML;ALERROR;BOOST;ALVALUE;TINYXML;ALERROR;BOOST" CACHE STRING "" FORCE)
mark_as_advanced(ALSOAP_DEPENDS)

set(ALSOAP_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALSOAP_DEFINITIONS)
 

find_library(ALSOAP_DEBUG_LIBRARY alsoap_d)
find_library(ALSOAP_LIBRARY       alsoap)


if (ALSOAP_DEBUG_LIBRARY)
  set(ALSOAP_LIBRARIES optimized;${ALSOAP_LIBRARY};debug;${ALSOAP_DEBUG_LIBRARY})
else()
  set(ALSOAP_LIBRARIES ${ALSOAP_LIBRARY})
endif()
set(ALSOAP_LIBRARIES "${ALSOAP_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALSOAP_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALSOAP DEFAULT_MSG
  ALSOAP_LIBRARIES
  ALSOAP_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALSOAP_PACKAGE_FOUND ${ALSOAP_FOUND} CACHE INTERNAL "" FORCE)
 