/**
* @author Cyrille Collette
* Copyright (c) Aldebaran Robotics 2011 All Rights Reserved
*/
#pragma once

#ifndef _LIB_ALMOTION_ALMODELUTILS_MODEL_TYPES_ALCOLLISIONSHAPE_UTILS_H_
#define _LIB_ALMOTION_ALMODELUTILS_MODEL_TYPES_ALCOLLISIONSHAPE_UTILS_H_

namespace AL
{
namespace Motion
{

enum COLLISION_SHAPE {
  COLLISION_SHAPE_SPHERE  = 0,
  COLLISION_SHAPE_PLAN    = 1,
  COLLISION_SHAPE_PILL    = 2
};

}
}
#endif  // _LIB_ALMOTION_ALMODELUTILS_MODEL_TYPES_ALCOLLISIONSHAPE_UTILS_H_
