# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALLOG_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALLOG_INCLUDE_DIRS)
   
set(ALLOG_DEPENDS "ALCORE;ALTOOLS;BOOST_SIGNALS;BOOST;QI;ALERROR;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;ALCORE;ALTOOLS;BOOST_SIGNALS;BOOST;QI;ALERROR;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL" CACHE STRING "" FORCE)
mark_as_advanced(ALLOG_DEPENDS)

set(ALLOG_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALLOG_DEFINITIONS)
 

find_library(ALLOG_DEBUG_LIBRARY allog_d)
find_library(ALLOG_LIBRARY       allog)


if (ALLOG_DEBUG_LIBRARY)
  set(ALLOG_LIBRARIES optimized;${ALLOG_LIBRARY};debug;${ALLOG_DEBUG_LIBRARY})
else()
  set(ALLOG_LIBRARIES ${ALLOG_LIBRARY})
endif()
set(ALLOG_LIBRARIES "${ALLOG_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALLOG_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALLOG DEFAULT_MSG
  ALLOG_LIBRARIES
  ALLOG_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALLOG_PACKAGE_FOUND ${ALLOG_FOUND} CACHE INTERNAL "" FORCE)
 
if(NOT ALLOG_I_KNOW_IT_IS_DEPRECATED AND QI_WARN_DEPRECATED)
  message(STATUS "
    ${CMAKE_CURRENT_SOURCE_DIR}: allog is deprecated
    Please use qi::log instead.
  "
  )
  set(ALLOG_I_KNOW_IT_IS_DEPRECATED ON)
endif()
