# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(ALSERIAL_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALSERIAL_INCLUDE_DIRS)
   
set(ALSERIAL_DEPENDS "QI;TINYXML;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;QI;TINYXML;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL" CACHE STRING "" FORCE)
mark_as_advanced(ALSERIAL_DEPENDS)

set(ALSERIAL_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(ALSERIAL_DEFINITIONS)
 

find_library(ALSERIAL_DEBUG_LIBRARY alserial_d)
find_library(ALSERIAL_LIBRARY       alserial)


if (ALSERIAL_DEBUG_LIBRARY)
  set(ALSERIAL_LIBRARIES optimized;${ALSERIAL_LIBRARY};debug;${ALSERIAL_DEBUG_LIBRARY})
else()
  set(ALSERIAL_LIBRARIES ${ALSERIAL_LIBRARY})
endif()
set(ALSERIAL_LIBRARIES "${ALSERIAL_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(ALSERIAL_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ALSERIAL DEFAULT_MSG
  ALSERIAL_LIBRARIES
  ALSERIAL_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(ALSERIAL_PACKAGE_FOUND ${ALSERIAL_FOUND} CACHE INTERNAL "" FORCE)
 