# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(TINYXML_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(TINYXML_INCLUDE_DIRS)
   
set(TINYXML_DEPENDS "" CACHE STRING "" FORCE)
mark_as_advanced(TINYXML_DEPENDS)

set(TINYXML_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(TINYXML_DEFINITIONS)
 

find_library(TINYXML_DEBUG_LIBRARY tinyxml_d)
find_library(TINYXML_LIBRARY       tinyxml)


if (TINYXML_DEBUG_LIBRARY)
  set(TINYXML_LIBRARIES optimized;${TINYXML_LIBRARY};debug;${TINYXML_DEBUG_LIBRARY})
else()
  set(TINYXML_LIBRARIES ${TINYXML_LIBRARY})
endif()
set(TINYXML_LIBRARIES "${TINYXML_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(TINYXML_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TINYXML DEFAULT_MSG
  TINYXML_LIBRARIES
  TINYXML_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(TINYXML_PACKAGE_FOUND ${TINYXML_FOUND} CACHE INTERNAL "" FORCE)
 