# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(RTTOOLS_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(RTTOOLS_INCLUDE_DIRS)
   
set(RTTOOLS_DEPENDS "QI;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;RT;QI;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;RT" CACHE STRING "" FORCE)
mark_as_advanced(RTTOOLS_DEPENDS)

set(RTTOOLS_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(RTTOOLS_DEFINITIONS)
 

find_library(RTTOOLS_DEBUG_LIBRARY rttools_d)
find_library(RTTOOLS_LIBRARY       rttools)


if (RTTOOLS_DEBUG_LIBRARY)
  set(RTTOOLS_LIBRARIES optimized;${RTTOOLS_LIBRARY};debug;${RTTOOLS_DEBUG_LIBRARY})
else()
  set(RTTOOLS_LIBRARIES ${RTTOOLS_LIBRARY})
endif()
set(RTTOOLS_LIBRARIES "${RTTOOLS_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(RTTOOLS_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RTTOOLS DEFAULT_MSG
  RTTOOLS_LIBRARIES
  RTTOOLS_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(RTTOOLS_PACKAGE_FOUND ${RTTOOLS_FOUND} CACHE INTERNAL "" FORCE)
 