# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(LIBFILE_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(LIBFILE_INCLUDE_DIRS)
   
set(LIBFILE_DEPENDS "ALTOOLS;ALCORE;QI;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;ALERROR;ALTOOLS;ALCORE;QI;BOOST_FILESYSTEM;BOOST_THREAD;BOOST_DATE_TIME;PTHREAD;DL;ALERROR" CACHE STRING "" FORCE)
mark_as_advanced(LIBFILE_DEPENDS)

set(LIBFILE_DEFINITIONS "" CACHE STRING "" FORCE)
mark_as_advanced(LIBFILE_DEFINITIONS)
 

find_library(LIBFILE_DEBUG_LIBRARY alfile_d)
find_library(LIBFILE_LIBRARY       alfile)


if (LIBFILE_DEBUG_LIBRARY)
  set(LIBFILE_LIBRARIES optimized;${LIBFILE_LIBRARY};debug;${LIBFILE_DEBUG_LIBRARY})
else()
  set(LIBFILE_LIBRARIES ${LIBFILE_LIBRARY})
endif()
set(LIBFILE_LIBRARIES "${LIBFILE_LIBRARIES}" CACHE STRING "" FORCE)
mark_as_advanced(LIBFILE_LIBRARIES)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBFILE DEFAULT_MSG
  LIBFILE_LIBRARIES
  LIBFILE_INCLUDE_DIRS
)
# Right after find_package_handle_standard_args, _FOUND is
# set correctly.
# For instance, if foo/bar.h is not foud, FOO_FOUND is FALSE.
# But, right after this, since foo-config.cmake HAS been found, CMake
# re-set FOO_FOUND to TRUE.
# So we set _PACKAGE_FOUND in cache...
set(LIBFILE_PACKAGE_FOUND ${LIBFILE_FOUND} CACHE INTERNAL "" FORCE)
 
message(WARNING ${CMAKE_CURRENT_LIST_FILE}"
  Usage of :
    use_lib(... LIBFILE)
  is deprecated
  Use:
    qi_use_lib(... alfile)
    or
    use_lib(... ALFILE)
   instead
")
